ResumeProjectWeb/Controllers/ContactAddressController.cs
using AutoMapper;
using Core.DTOs;
using Core.Entities;
using Core.Services;
using Microsoft.AspNetCore.Mvc;
using Service.Services;

namespace ResumeProjectWeb.Controllers
{
    public class ContactAddressController : Controller
    {
        private readonly IContactAddressService _contactAddressService;
        private readonly IMapper _mapper;

        public ContactAddressController(IContactAddressService contactAddressService, IMapper mapper)
        {
            _contactAddressService = contactAddressService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var values = await _contactAddressService.GetAllAsync();
            

            return View(_mapper.Map<IEnumerable<ContactAddressDto>>(values));
           
        }

        public async Task<IActionResult> DeleteContact(int id)
        {
            var value = await _contactAddressService.GetByIdAsync(id);
            await _contactAddressService.RemoveAsync(value);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> UpdateContact(int id)
        {
            var value = await _contactAddressService.GetByIdAsync(id);

            return View(_mapper.Map<ContactAddressDto>(value));            
        }
        [HttpPost]
        public async Task<IActionResult> UpdateContact(ContactAddressDto contactAddressDto)
        {
            var value = _mapper.Map<ContactAddress>(contactAddressDto);
            await _contactAddressService.UpdateAsync(value);
            return RedirectToAction("Index");

        }
    }
}

ResumeProjectWeb/Views/ContactAddress/Index.cshtml
@model IEnumerable<ContactAddressDto>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>İletişim Sayfası</h1>

<table class="table table-bordered">
    <tr>

        <th>Adres</th>
        <th>E-Mail</th>
        <th>Telefon</th>       
        <th>Sil</th>        
        <th>Düzenle</th>        
    </tr>


    @foreach (var item in Model)
    {
            <tr>

                <td>@item.Address</td>
                <td>@item.Email</td>
                <td>@item.Phone</td>                

            @*<td><a href="/Experience/DeleteExperience/@item.Id"  class="btn btn-danger">Delete</a></td>*@
                <td><a asp-action="DeleteContact" asp-controller="ContactAddress" asp-route-id="@item.Id" class="btn btn-danger" onclick="return confirm('Silme işlemi onaylansın mı?')">Sil</a></td>
            
                <td><a asp-action="UpdateContact" asp-controller="ContactAddress" asp-route-id="@item.Id" class="btn btn-danger">Güncelle</a></td>
            </tr>
    }
</table>

ResumeProjectWeb/Views/ContactAddress/UpdateContact.cshtml
@model ContactAddressDto
@{
    ViewData["Title"] = "UpdateContact";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Adres Güncelleme Sayfası</h1>

<form class="form-group" method="post">
    <input type="text" asp-for="Address" class="form-control" placeholder="Adres bilgisi giriniz..." />
    <br />
    <input type="text" asp-for="Email" class="form-control" placeholder="Email giriniz..." />

    <textarea asp-for="Phone" class="form-control" placeholder="Telefon Numarası Giriniz..." rows="5"></textarea>
    <br />
    <button class="btn btn-info">Güncelle</button>
</form>